apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poc-initcontainer-app.fullname" . }}
  labels:
    {{- include "poc-initcontainer-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "poc-initcontainer-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "poc-initcontainer-app.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: "{{ .Chart.Name }}-internal-event-bus-init"
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          env:
            {{- include "helpers.list-env-variables" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "helpers.list-env-variables" . | indent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
